apt update when adding mozilla repo

diff --git a/debian/neon-repositories-mozilla-firefox.postinst b/debian/neon-repositories-mozilla-firefox.postinst
--- a/debian/neon-repositories-mozilla-firefox.postinst
+++ b/debian/neon-repositories-mozilla-firefox.postinst
@@ -55,6 +55,12 @@ Signed-By: /etc/apt/keyring/org.kde.neon.packages.mozilla.org.asc
 EOF
 fi
 
+# Refresh the cache if it doesn't already contain the repo. This appears to be doable since updates
+# don't claim the lock. Whether it's sane to do is another question entirely...
+if ! apt-get indextargets | grep --quiet --extended-regexp '^Repo-URI:.+packages.mozilla.org' && [ "$JOB_NAME" = "mgmt_daily_promotion_jammy_release" ]; then
+  apt-get update || true # don't crap out on errors here
+fi
+
 # dh_installdeb will replace this with shell code automatically
 # generated by other debhelper scripts.
 
